name: Build Dynamic Library
on:
  push:
  release:
    types: [published]
jobs:
  build_lib:
    name: Build dynamic library on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-13, macos-latest]
    defaults:
      run:
        working-directory: cpp-bindings-test/
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build library
        run: |
          nix build
          ls -lR result/
      - uses: actions/upload-artifact@v4
        with:
          name: lib-${{ matrix.os }}
          path: cpp-bindings-test/result/lib/*
  build_lib_windows:
    name: Build dynamic library on windows
    runs-on: windows-latest
    defaults:
      run:
        working-directory: cpp-bindings-test/
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Build library
        run: |
          cmake -B build -G "Visual Studio 17 2022"
          cmake --build build --config Release
          cmake --build build --config Release -t RUN_TESTS
      - uses: actions/upload-artifact@v4
        with:
          name: lib-windows-latest
          path: cpp-bindings-test/build/Release/*.dll
