name: Build Python Bindings
run-name: Build Python Bindings (${{ github.sha }})
on:
  workflow_run:
    workflows: ["Build Dynamic Library"]
    types: [completed]
jobs:
  build_sdist:
    name: Build python sdist
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    defaults:
      run:
        working-directory: bindings/python
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: bindings/python/pyproject.toml
      - name: Build sdist
        run: uv build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: python-sdist
          path: bindings/python/dist/*.tar.gz
  build_wheel:
    name: Build python wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: github.event.workflow_run.conclusion == 'success'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # , ubuntu-24.04-arm, macos-13, macos-latest
    defaults:
      run:
        working-directory: bindings/python
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: bindings/python/pyproject.toml
      - uses: actions/download-artifact@v4
        with:
          name: lib-${{ matrix.os }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: bindings/python/artifacts
      - name: Copy prebuilt-library into source tree
        shell: bash
        run: |
          if [ "$RUNNER_OS" != "Windows" ]; then
            cp -r artifacts/lib cpp-bindings-test/lib
          else
            cp -r artifacts/bin cpp-bindings-test/lib
          fi
      - name: Build wheel
        run: uv build --wheel
      - uses: actions/upload-artifact@v4
        with:
          name: python-wheel-${{ matrix.os }}
          path: bindings/python/dist/*.whl
