name: Build Python Bindings
on:
  push:
  release:
    types: [published]
jobs:
  build_sdist:
    name: Build python sdist
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bindings/python
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: bindings/python/pyproject.toml
      - name: Build sdist
        run: uv build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: python-sdist
          path: dist/*.tar.gz
  build_wheel:
    name: Build python wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-latest]
    defaults:
      run:
        working-directory: bindings/python
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: bindings/python/pyproject.toml
      - uses: actions/download-artifact@v4
        with:
          name: lib-${{ matrix.os }}
          path: bindings/python/lib
      - run: ls -la bindings/python/lib
      - name: Build wheel
        run: uv build --wheel
      - uses: actions/upload-artifact@v4
        with:
          name: python-wheel-${{ matrix.os }}
          path: dist/*.whl
